### PR TITLE
Revamp homepage layout

### PR DESCRIPTION
**Pull request by ayoisaiah**
Summary: I swapped out the CSS boilerplate and revamped the homepage layout. Here's a full page screenshot:

albert-homepage-3

Changes made:
- Redesign top navigation
- Add hamburger menu and navigation overlay for mobile screens
- Add footer
- Add screenshots
- Remove Milligram in favor of Skeleton
- Add content to homepage

### CODE REVIEW

**Comment by Fuhrmann** [comment]
Wow! Pretty nice.

**Comment by Fuhrmann** [comment]
@ayoisaiah  We have a theme editor (https://albertlauncher.github.io/docs/theming/themecreator/). Do you think you can make more visible at the home page? 

@ManuelSchneid3r what do you think?

**Comment by ayoisaiah** [comment]
Thanks @Fuhrmann ! I suppose I could add it to the top navigation.

**Comment by ayoisaiah** [comment]
@Fuhrmann @ManuelSchneid3r 
navigation bar v2

**Comment by Fuhrmann** [comment]
Hey @ManuelSchneid3r, did you consider merging this?

**Comment by bebehei** [comment]
Wow, this is a cool thing. @ManuelSchneid3r Since this PR is unanswered for a long time, do you have any objections merging this?

**Comment by ManuelSchneid3r** [comment]
Sure but it a huge bunch of code to review… :unamused:

**Comment by ManuelSchneid3r** [comment]
@ayoisaiah I just wanted to merge this PR finally, but then I realized that this is an "unknown repository".

**Comment by bebehei** [comment]
@ManuelSchneid3r I guess he has deleted his for in meantime. But the commits should still be available here. So, I guess this shouldn't be a problem when merging this PR.

**Comment by Fuhrmann** [comment]
@ayoisaiah do you still have the code?

**Comment by bebehei** [comment]
> @ayoisaiah do you still have the code?

@Fuhrmann The code is still here.

```
git clone https://github.com/albertlauncher/documentation
cd documentation
git fetch origin refs/pull/8/head:revampcd-hp
git checkout revamp-hp
```

**Comment by Fuhrmann** [comment]
Well, then the merge is fine. This would be a great revamp to the site.

**Pull request closed without merging**
