### PR TITLE
adding Gentoo setup command

### PR DESCRIPTION
**Pull request by CaseOf**

### CODE REVIEW

**Review by BlueManCZ — COMMENTED** [review]
Shouldn't it be unified whether to use `sudo` or not?

**Comment by CaseOf** [comment]
Probably not, I log in as root on my computers on doing these operations.
I mean, it’s optional and depend on user preferences.
Gentoo is all about choice as they like to say in their introduction.

**Comment by ManuelSchneid3r** [comment]
It should. No sudo.

**Comment by BlueManCZ** [comment]
Yes, I mean it looks strange when you have sudo in Arch and Void commands, and then not in SUSE and Gentoo.

**Comment by ManuelSchneid3r** [comment]
Sure I'll change this

**Pull request merged**
